apiVersion: v1
kind: ReplicationController
metadata:
  name: rcmavenwebapplication
  namespace: inviz-ns
spec: 
  replicas: 4
  selector:
    name: maven
  template: 
    metadata: 
      name: rcpodname
      labels:
        name: maven
    spec:
      containers:
      - name: rcontainername
        image: mrrowdy/mavenwebapplicationamechandra:1
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: svcname
  namespace: inviz-ns
spec: 
  type: NodePort
  selector: 
    name: maven
  ports: 
  - port: 80
    targetPort: 8080

